import sys
from docx import Document

doc = Document()
doc.add_heading('Part III: Eastern & Western Self', level=1)
doc.add_paragraph('One of the most influential people in my life who inspired me to take my current course is my Kuya. When we were younger and living in Balibago, I often accompanied him to computer shops, where I discovered video games. What started as simple enjoyment slowly turned into curiosity about how computers worked, which eventually led me to pursue a course related to technology. As a teen entering her twenties, the value that I take from Eastern perspectives on the self, particularly the Confucian principle of considering others before oneself. His respectful way of treating people and his sense of responsibility shaped how I interact with others. I see this reflected in my own belief of "Don\'t do unto others what you don\'t want done unto you" showing how relational and moral values continue to guide my choices.')
doc.add_paragraph('As I grew older, I also developed traits influenced by Western perspectives, especially the idea of independence and individualism. I enjoy doing things on my own, making my own decisions, and being responsible for my personal growth. This habit reflects the Western view of the self as independent and self-directed. While Eastern culture emphasizes family and community, my preference for independence sometimes puts me in between these two perspectives. There are moments when I struggle to balance being self-reliant while still valuing close family ties, but this combination ultimately shapes my identity. It allows me to value personal freedom without losing respect for relationships and shared responsibilities.')
doc.add_paragraph('These blended perspectives became more evident when I traveled to Singapore and experienced cultural differences firsthand. I noticed how discipline, efficiency, and respect for rules were deeply embedded in everyday life, which felt different from what I was used to in the Philippines. Instead of resisting these differences, I observed and learned from them. As a BSIT student, these experiences are valuable because working or migrating abroad is common in my field. Understanding different cultures helps me adapt more easily and work better with diverse teams. In the future, I can promote cultural empathy by being open-minded, respectful of different practices, and considerate when collaborating with people from various backgrounds, especially in global or multicultural work environments.')

doc.add_heading('Part IV: Philosophical & Psychological Self', level=1)
doc.add_paragraph('A defining moment in my life that shaped how I see myself was when I joined a volunteer program in my community. I worked with children who didn\'t have many opportunities, helping them with schoolwork and life skills. At first, it was challenging and sometimes discouraging, but I realized that patience, consistency, and genuine effort made a big difference in their lives. From this, I learned the meaning of "Pag nag-tanim ng maayos, may butid", if you put in care and effort, growth will follow. This philosophy now guides me: small, steady actions lead to meaningful results over time.')
doc.add_paragraph('Right now, I see myself as hardworking, curious, and determined, but I know I still struggle with procrastination and self-doubt. My dreams are to grow in my chosen field, develop my skills, and help others along the way. Ten years from now, I hope my future self remembers that growth is a process and that rewards come from consistent effort, not instant results. I want to stay patient, kind, and focused on the small steps that build long-term success. By embracing challenges and learning from mistakes, I can become the confident and capable person I hope to be.')
doc.add_paragraph('When I think about my real self and ideal self, I notice that they are not fully aligned yet. I am trying to balance ambition with patience, learning to trust that steady effort produces real results. A moment that showed me this was leading a group project in school, where I had to guide my team despite doubts and challenges. By focusing on planning, communication, and effort, I was able to help the team succeed and grow alongside them. Experiences like this remind me that if I nurture my actions carefully, just like planting seeds, I will eventually see the fruits of my work.')

doc.add_heading('Part IX: Parting Words', level=1)
doc.add_paragraph('Reflecting on the beginning of this semester, the course "Understanding the Self" has genuinely transformed my perspective on my identity in substantial and meaningful ways.')
doc.add_paragraph('I have learned that the self is not a static entity. It is a dynamic construction influenced by culture, upbringing, relationships, beliefs, possessions, and physical presence. I embody a blend of Eastern and Western values, philosophical and psychological insights, social and individual traits, as well as physical and spiritual dimensions.')
doc.add_paragraph('The most significant realization I take away is that self-awareness is a continuous practice rather than a final destination. This semester provided the analytical framework necessary to continually assess my identity and future aspirations.')
doc.add_paragraph('Moving forward, I am committed to continuous personal development. I resolve to strive for a version of myself that is inquisitive, compassionate, and intentional. I will prioritize effective time management, lead with empathy, and recognize that personal growth requires patience and sustained effort.')
doc.add_paragraph('I am profoundly grateful for the insights gained from this course and the unexpected depth of self-discovery it facilitated.')

doc.save('Plagscan_Submission_Parts_III_IV_IX.docx')
print('Docx created successfully.')
