import sys
from docx import Document

doc = Document()
doc.add_heading('Part III: Essay (Introduction)', level=1)
doc.add_paragraph('Everybody carries layers. Half-remembered stories, random thoughts that hit at 2 AM, small moments you didn\'t think mattered until they did. When I was trying to come up with a title for this portfolio, I kept coming back to "Unfolding Me." It wasn\'t something I overthought. It just felt true to what this whole semester actually was.')
doc.add_paragraph('I won\'t pretend Understanding the Self was just another class I needed to pass. Somewhere between the readings and the reflection papers, it started getting personal. I found myself thinking about things I\'d never really sat with before. How the culture I was raised in quietly shaped my opinions, how the people around me influenced what I thought was normal, how even the way I see my own body is tied up in so much more than I realized. These weren\'t just essay topics anymore. They were actually about me.')
doc.add_paragraph('The title stuck because I think that\'s genuinely how self-discovery works. You don\'t just wake up one day and suddenly know who you are. It\'s more like unfolding something, a letter, a map, a crumpled piece of paper, and noticing the creases. Those creases are the experiences and the hard seasons and the people who left a mark. They\'re not flaws. They\'re the whole point.')
doc.add_paragraph('So this portfolio is my attempt at documenting that process honestly. You\'ll find my reflections on the post-assessment modules, what I actually think about the SMART goals I set, and a few moments where something genuinely clicked for me. It\'s not a perfect collection but it\'s a real one.')

doc.add_heading('Part IV: SMART Goal Reflection', level=1)
doc.add_paragraph('Somewhere around midterms, I made myself a promise. No more pulling near-all-nighters just to submit something I wasn\'t even proud of. I set a goal to finish assignments at least two days early so I\'d have breathing room, time to actually read what I wrote before turning it in.')
doc.add_paragraph('Honestly? I half-kept it. There were weeks where I genuinely had it together and it felt amazing. Then there were other weeks where I\'d look up and it was suddenly 1 AM and I was back to panicking. But even the weeks I fell short taught me something I don\'t think I would\'ve learned otherwise. Big tasks feel impossible until you cut them down into something you can actually start. The goal itself was solid. My follow-through just wasn\'t consistent enough yet.')
doc.add_paragraph('What I\'m taking away from this isn\'t failure. It\'s that having a goal isn\'t enough on its own. I need a daily habit to back it up. Right now I\'m trying something small, just 20 minutes every morning to look over what\'s ahead and plan the day. It sounds almost too simple, but it\'s been working better than any big dramatic overhaul I\'ve tried before. Consistency really does beat intensity. And planning ahead doesn\'t just cut stress. It\'s the difference between work I rush through and work I can actually stand behind.')

doc.add_heading('Part XI: Essay / Parting Words', level=1)
doc.add_paragraph('I thought about who I was on the first day of this semester, and I genuinely don\'t think I\'d describe myself the same way now. That\'s not me being dramatic. The shift is real, even if it\'s quiet.')
doc.add_paragraph('The thing that hit me hardest was realizing that identity isn\'t fixed. It\'s not some permanent version of yourself you either have or don\'t. It moves. It adjusts. It responds to relationships and failures and tiny decisions you make on random Tuesday afternoons. I used to think my flaws were the opposite of my strengths, like one canceled the other out. Now I think they\'re just different parts of the same person, and both are worth understanding.')
doc.add_paragraph('I also had to make peace with the fact that self-awareness doesn\'t have an endpoint. You don\'t figure yourself out and then stop. I\'m not going to have everything sorted by graduation, and maybe that\'s actually fine. What this course gave me was less about answers and more about learning to ask better questions, about why I do what I do, what I actually want, and what kind of person I\'m trying to become.')
doc.add_paragraph('Going forward, I want to hold onto that. I want to be more deliberate, more patient with myself, and genuinely kinder to the people around me. More than anything, I\'m grateful this course gave me room to be honest, not just in the assignments, but with myself. Because underneath all the modules and reflection papers, that\'s what it really was. A chance to sit down, get quiet, and actually listen to the person I\'ve been becoming all along.')

doc.save('Plagscan_Submission_Parts_III_IV_XI.docx')
print('Docx created successfully.')
